remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: RunLang
description: A c++ based language to bring the ease of python to the speed of c
show_downloads: true