remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme 

title: RunLang
description: A c++ based language to bring the ease of python to the speed of c
show_downloads: true
nav_order: 4
has_children: true